### ISSUE TITLE
Right-click not working on mac

### ISSUE THREAD

**Issue by rbren** [BespokeSynth/BespokeSynth#107]
I'm not able to right-click or control-click to bring up the LFO.

Happy to take a look at the code if you can point me in the right direction

**Comment by westurner** [comment]
Right-click and Ctrl-click on the empty workspace and on things also appears to do nothing on Linux. (Where, on a Macbook, i have to press `shift-delete` to do backspace to delete a patch, which requires three fingers; just 'delete'='backspace'='delete_patch' would be great)

**Comment by awwbees** [comment]
ahh, on a mac, I have always used two-finger-click to right click. it does seem that ctrl-click doesn't work in bespoke, because I wasn't using the correct method to detect multiplatform right clicks.

it looks like an easy fix: in https://github.com/awwbees/BespokeSynth/blob/master/Source/MainComponent.cpp, just replace every call to `isRightButton()` with `isPopupMenu()`. I will test this out to make sure this doesn't cause any other issues, but if you're eager for the fix and want to build for yourself, that is probably it!

**Comment by awwbees** [comment]
fixed in b513c07bd1ceb6cb48fdf192272e71347a3986a8, will be in release 1.0.1
