### ISSUE TITLE
GPL-2 licence being violated

### ISSUE THREAD

**Issue by lpil** [BespokeSynth/BespokeSynth#115]
Hello! Thanks for this excellent program!

The xwax code used by the timecode vinyl module is licenced under GPL-2, so inclusion in this GPL-3 program is a licence violation.

https://github.com/awwbees/BespokeSynth/blob/cf3465115baeedce810567c54bd2c24ce9f1d082/Source/vinylcontrol/timecoder.h#L2-L16

The good news is that a month ago xwax moved to GPL-3 (https://github.com/xwax/xwax/commit/593cbb1743fd444bdf4229a5aec5c3c02c804cae) so if Bespoke upgrades to the latest version then it will no longer be violating the licence.

Cheers,
Louis

**Comment by tmilker** [comment]
Alternatively, he can just license his code under both GPL v2 and GPL v3.

**Comment by awwbees** [comment]
thank you for this heads up. I am currently working on this, unfortunately it is a complex upgrade. it turns out that my code was actually based upon https://github.com/lodsb/vinylcontrol, which was using a modified version of xwax, and is still GPL2 (besides the fact that the xwax API has changed significantly since then anyway)

so, I'm looking at the xwax code and trying to figure out how to recreate the functionality

**Comment by lpil** [comment]
Awesome, thank you. There's a (rather quiet) mailing list where Mark and the others may be able to help with any specifics. 

https://xwax.org/contact.html

**Comment by awwbees** [comment]
managed to get it all working! thank you again

**Comment by lpil** [comment]
Wow that was fast! Thank you very much￼
