### ISSUE TITLE
Window seemingly softlocks/disables input at random

### ISSUE THREAD

**Issue by Technochips** [BespokeSynth/BespokeSynth#123]
On Windows 10

At completely random times (maybe at heavy CPU usage?), the window completely locks up and it will receive no input. The program will continue to play audio, but it won't respond to any mouse clicks or buttons presses. Even the titlebar won't respond, and you won't be able to close the window normally (it is however possible to close the program through the taskbar). This is slightly infuriating because at that point, you won't be able to save the progress you made.

**Comment by Technochips** [comment]
Seems to also happen with file selection dialogs, they get locked up.

**Comment by awwbees** [comment]
I'll be taking a look at this soon. I have a slight suspicion that it might be related to displays in some way, like you could trigger this by plugging in or removing a monitor, causing windows to reset it display settings, which maybe has some lockup effect on bespoke. I will try to reproduce this issue, but maybe that information is also helpful to you in narrowing down what might be causing it

edit: confirmed that I can reproduce this 100% by plugging in a monitor, or unplugging a monitor. technical details that I'm still trying to figure out: it appears that when you are in this state, lpfnWndProc stops being called

**Comment by Technochips** [comment]
Edit: you're probably right. Noticed it happened when my wallpaper changed (with automatic accent color). I'll have to see if not having a gallery wallpaper fixes it.

edit: it didn't

**Comment by awwbees** [comment]
ooh, this is great info! I'll find a fix, but hopefully disabling that is a good temporary workaround for you

**Comment by portalhugger** [comment]
I had a much more catastrophic version of the same issue -- when disconnecting my second monitor, no less. All applications that were open when I disconnected it ceased responding to clicks, and Alt+Tab wouldn't swap between windows either. I had to bring up task manager, which did respond, in order to close everything else (losing all my progress in bespoke! D:)
I closed bespoke last in the hopes another program was causing the problem, so I'm not sure if stopping bespoke is what resolved the issue.
Windows 10. Bespoke was on my primary monitor, not my second. High-quality gaming PC. Second monitor is a toshiba TV with smaller resolution than my primary screen.
