### ISSUE TITLE
can't find installed VST on Mac 10.15.7

### ISSUE THREAD

**Issue by rbnpi** [BespokeSynth/BespokeSynth#137]
NO VST shown when plugins list is clicked on my Mac, even though they are there in the correct locations, and are useable with other DAWs. Paths correct in vstsearchdirectories field in settings.

**Comment by singulararmchair** [comment]
I'm on 10.13.6 and can't see them either. Scanning causes Bespoke to hang, need to force-quit.
EDIT: Found the problem. Five12 Numerology VST caused the hang. Removed from the folder and the scan was able to finish.

I don't know if your problem is the same as mine, but to troubleshoot, right-click on Bespoke -> Show Package Contents, then navigate to Contents->Mac OS->Bespoke. Look at the Terminal output when attempting to scan

**Comment by awwbees** [comment]
like #112, it sounds like I need to figure out a better solution for VST scanning. noted!

**Comment by rbnpi** [comment]
built from latest source (commit #213) and now working on my Mac.

**Comment by lalo** [comment]
It might be a permissions error, Mac OS X as of lately is very strict with downloaded apps not from the app store. Try giving it permission (either to the dir or full disk access via System Preferences). That worked for me, it did take a long time to scan all the apps and it appeared to be frozen but I noticed on the Activity Monitor that the threads were fluctuating even if it was unresponsive.

**Comment by awwbees** [comment]
I believe all these big sur permissions issues are fixed and will be in the 1.0.1 release
