### ISSUE TITLE
Quirks of LFOs with custom slider ranges

### ISSUE THREAD

**Issue by disconex** [BespokeSynth/BespokeSynth#139]
Duplicating, loading and reconnecting LFOs tends to go wrong when there are custom slider ranges involved.

For example, when I instantiate an oscillator and make its pulse-width slider go from 0.25 to 0.75, then create an LFO modulating that slider over that range, it is then possible to duplicate that LFO with all settings intact by alt/option-dragging. However, when I leave the oscillator settings at their defaults and change the ranges of the LFO's ‘low’ and ‘high’ sliders to 0.25–0.75 instead, the LFO's clone will copy the values of those sliders, but inherit the ranges for those sliders from the oscillator's pulse-width slider.

![lfo-slider-range-problem](https://user-images.githubusercontent.com/90849955/133669724-cb804c9c-105b-4b1a-918a-b76b25a02674.png)

When saving the LFO with a prefab and then loading the prefab, the slider ranges are initially as saved, but when the output is connected to its target, they again inherit the range of the target slider. Also upon making the connection, the low and high values, both from within a prefab and from a bare LFO, both copy the target slider's current value.

**Comment by awwbees** [comment]
thank you for the detailed report! I will dig through the issues that are causing this.

**Comment by spectromas** [comment]
I'm experiencing similar things with the LFOs as well but in a simpler way. For me, at some point, the ranges of the LFO disengages from the green sliders and the low/high have no effect at all. 

I've just noticed that if I pin the LFO and delete it, set the parameter to centre and then try to enable LFO again the low/high range still has no effect. 

Is there a way to move the left green range slider?

**Comment by awwbees** [comment]
> Is there a way to move the left green range slider?

yes, it's a bit odd, but feels very natural once you get used to it: drag horizontally to adjust the range max, and vertically to adjust the range min

**Comment by NoxyNixie** [comment]
I think this issue is no longer an issue? The behavior of cloning and connecting LFO's (and other modulation) has changed a bit since this report.

If I change the `osccillator`s pw: sliders min and max ranges the newly cloned LFO after reconnecting will take those min and max ranges over.

If I change the original LFO's `min` and `max` ranges on its `low` and `high` sliders and clone it those ranges initially clone perfectly however it won't be connected. As soon as you connect that LFO it will read the ranges of the target slider and takes those over (which I think is intended behavior).

Also note that you now can't have two LFO modules connected to the same control anymore.

Please comment or post a new issue if this is still a problem and I'll reopen the issue ;)
