### ISSUE TITLE
LABS not showing full UI?

### ISSUE THREAD

**Issue by 1db1db** [BespokeSynth/BespokeSynth#141]
![image](https://user-images.githubusercontent.com/47069841/133691660-bf46a909-1d3e-4907-a791-0a272aa42e6a.png)
ive reinstalled the whole Spitfire Labs app, ive repaired all the individual labs, and nothings done anything. :(

**Comment by KottV** [comment]
is that a vst3 version? probably a JUCE bug

**Comment by awwbees** [comment]
hmm. this is not particularly helpful, but LABS does work for me, on both a hi-dpi monitor and a low-res monitor. this is a shot of the vst3 version, which eliminates that potential cause:
![image](https://user-images.githubusercontent.com/839239/133719422-da78e9b5-15be-416c-b4af-384194a85e4f.png)

one very suspicious thing is that the LABS window seems to be showing exactly 25% of the contents, which makes it seems like a hi-dpi rescaling issue. not sure would could be causing that.

potential weird workaround: if you hover over the lower-right corner of the window, do you get a resizing handle? what happens if you resize the window?

**Comment by 1db1db** [comment]
yeah the only things i can interact with are things inside the quadrant that shows up

**Comment by awwbees** [comment]
but how about resizing? is that possible?

**Comment by NoxyNixie** [comment]
I can't reproduce this on my end.

If this is still an problem please comment on this issue or post a new issue instead either way is good ;)
