### ISSUE TITLE
Bug: Out-of-domain function in waveshaper destroys downstream audio, looks like a case of `NaN`s

### ISSUE THREAD

**Issue by UniQMG522** [BespokeSynth/BespokeSynth#158]
When outside of the waveshaper's formula's domain (note the gap in the center), what I'm guessing are `NaN`s are passed downstream and destroy any audio they coincide with. The drum is only audible when the oscillator is playing in the function domain:

https://user-images.githubusercontent.com/48872143/133763214-aaf42e2b-54f8-4577-9373-58b1c1fab846.mp4

Bypassing the waveshaper makes the difference much more obvious:

https://user-images.githubusercontent.com/48872143/133763677-f84609ba-9f94-4efb-a4f0-c9e8568871af.mp4

If it is caused by `NaN`s, they should probably be replaced with `0`s.

**Comment by NoxyNixie** [comment]
In the latest nightly build these cables turn red (instead of disappearing). I thought maybe it would be nice to have an option that turns these `NaN`'s to `0` but this will likely affect performance of all buffer operation significantly. Even if it isn't a setting and we abolish any NaN's this alone means adding a check anywhere there is buffer access for NaN's.

So with 557950867433915ccf282e4d4de2ea9fce66c709 I think this issue is "fixed".

If you think that changing `NaN`'s to `0` is worth a potentially significant performance loss then feel free to reply and I'll reopen the issue.
