### ISSUE TITLE
sampler module always pitch-corrects the recorded audio, even if it is told not to

### ISSUE THREAD

**Issue by maxigaz** [BespokeSynth/BespokeSynth#1605]
## Describe the bug

The `sampler` module has a checkbox with the label 'pitch'. The tooltip says, 'should we attempt pitch-correct the audio? (sic)'. The problem is that pitch correction is applied even if the option is unchecked.

(As a side note, the resulting pitch is different depending on whether the option is checked, although in both cases, feeding higher note into the module still results in a higher pitch and lower notes in a lower pitch.)

## Build info

bespoke NIGHTLY 1.2.1 (Jun 20 2024 04:27:35) - Linux - HEAD 7891a7a

## Steps To Reproduce

1. Connect an audio source to `sample`. (I used Cardinal, but any built-in module from the synth category should work.)
2. Record some audio.
3. Trigger the sampler with MIDI notes to play the audio back.

## Expected vs. actual behavior

When 'pitch' is unchecked in `sampler`, I want it to never pitch correct the recorded sample, regardless of what note it is sent to.

**Comment by NoxyNixie** [comment]
I think this is a misunderstanding of the control. When the `pitch` checkbox is checked the module will attempt to detect the pitch of the sample and correct from there so that when you play a C3 note it sounds like a C3 note (does not always work with complex waveforms).

If the `pitch` checkbox is unchecked no correction is done and the sample is assumed to be at the correct pitch.

Notes with pitch information will always change the pitch of the `sampler` output. If you don't want this you can use a `pitchsetter` module before the `sampler` module.

**Comment by maxigaz** [comment]
> Notes with pitch information will always change the pitch of the `sampler` output. If you don't want this you can use a `pitchsetter` module before the `sampler` module.

What should I set `pitchsetter` to if I want the pitch to stay the same? After some quick testing, I found that setting it to the root note of the current scale does that, but I'm not sure anymore.

**Comment by NoxyNixie** [comment]
Sounds about right!
