### ISSUE TITLE
eq doesn't show waveform unless an output is connected

### ISSUE THREAD

**Issue by westurner** [BespokeSynth/BespokeSynth#1638]
## Describe the bug

The eq doesn't show the waveform of the inputs unless an output is connected, though the module it outputs to doesn't have to be connected to gain.

## Build info
```
bespoke 1.2.1 (Feb 19 2024 00:00:00) - Linux - unknown-branch deadbeef
```

## Steps To Reproduce

- notes instrument + synth + `eq`
- connect and disconnect `eq` from `gain`
- connect and disconnect `eq` from an `effectchain` (that's not even connected to `gain`)

## Expected vs. actual behavior
eq should show the waveform with parametric transforms when no output is connected.

**Comment by NoxyNixie** [comment]
Audio processing is skipping in many modules when their output is disconnected. This wil likely not be changed for modules that are meant to passthrough audio.

**Comment by westurner** [comment]
Does there need to be an eq2 in order to have an eq that can sample a patch
without an output connected?

Use case: isolate to find peaks anywhere, in order to level with least loss
of signal

There's no modeling of nonlinearity in patches, So why does there need to
be an output connected in order to process the input?

An option to add an eq to all patches on keyboard shortcut and/or checkbox
toggle would be cool and would also solve

**Comment by westurner** [comment]
Use case: press Shift to add an additional patch to an eq (that doesn't
need an output unless one is added later)

**Comment by NoxyNixie** [comment]
If you need the visual you can use the `waveformviewer` or `spectrum` for that.

> Does there need to be an eq2 in order to have an eq that can sample a patch without an output connected? 

I'm not sure what you mean here. You can always add a dummy `gain` module (that isn't connected to something else) after your `eq` module.

> Use case: isolate to find peaks anywhere, in order to level with least loss of signal 

Use the `waveformviewer` or `spectrum` for that or connect the output of the `eq` module to something.

> There's no modeling of nonlinearity in patches, 

Not sure what you mean with that?

> So why does there need to be an output connected in order to process the input?

Because equalization requires a audio buffer to work on. Modules get their audio buffer from the module they are connected to so they need to be connected. Some modules like the `waveformviewer` and `spectrum` have been modified to be an end point so they can display the waveform even when their outputs are not connected but the `eq` module clearly is not meant to be an endpoint.

> An option to add an eq to all patches on keyboard shortcut and/or checkbox toggle would be cool and would also solve

What is wrong with adding an `eq` module the normal way (there are a few options to adding modules like the double `shift` method)?

> Use case: press Shift to add an additional patch to an eq (that doesn't need an output unless one is added later)

I'm not sure what you mean here. You say "Use case" but then not describe one. You can already connect many cables to a single `eq` module?

**Comment by westurner** [comment]
So, as I understand it, you prefer this:

1. Add an eq module to the module to sample the waveform of
2. Add a gain module with no outputs to the eq module

To - I guess this is a feature request then - this:

1. Add an eq module a module's outputs

Which would make manually adding a waveform viewer to every output patched to the primary gain easier.

A script and then a ui element and keyboard shortcut to add a eq or a waveformviewer next to *every* patched output would also solve for the general audio leveling and parametric waveforming use case.

If a script adds an eq ~waveformviewer to every patched output, there's then no way to upgrade that to have an output~ [the user could then] patch to the primary gain to 'solo' that module output to the monitors.

If a karplusstrong can include a biquad, could an eq module include a gain at 1.0 unless there are outputs connected?

**Comment by westurner** [comment]
(There's backfeed on the line with really pro analog circuit simulators because there is nonlinearity to model that matters for those applications. 

In BespokeSynth, there must be an output module with an output buffer, but its parameters don't affect its inputs' outputs so there isn't nonlinearity?)

**Comment by westurner** [comment]
Adding an effectschain works too:

1 Add an eq module to the module to sample the waveform of
2. Add a gain or an effectschain module with no outputs to the eq module

So, a script would need to: find all patched outputs that transitively connect to the primary gain, and attach an eq and an effectschain module *next to* each (just as a user would do with shift to add an additional patch)

**Comment by westurner** [comment]
There may be additional undefined behavior here on second look:

1. Add a fouronthefloor ff1
2. Add a karplustrong ks1 to ff1
3. Add a waveformviewer wf1 to ks1

```
ff1 -> ks1 -> wf1
```
- [ ] No waveform on wf1


4. Patch waveformviewer wf1 to primary gain g0

```
ff1 -> ks1 -> wf1 -> g0
```

- [x] Waveform on wf1

5. Disconnect wf1 from g0

```
ff1 -> ks1 -> wf1
```

- [ ] No waveform on wf1

5. Duplicate from steps 1,2,3:

```
ff1 -> ks1 -> wf1
ff2 -> ks2 -> wf2
```
- [ ] No waveform on wf1.
- [ ] No waveform on wf2.

6. Attach either waveformviewer wf1 or wf2 to the primary gain g0:

```
ff1 -> ks1 -> wf1 -> g0
ff2 -> ks2 -> wf2
```
- [x] Waveform on wf1.
- [x] Waveform on wf2.

```
ff1 -> ks1 -> wf1
ff2 -> ks2 -> wf2 -> g0
```
- [x] Waveform on wf1.
- [x] Waveform on wf2.

**Comment by westurner** [comment]
After step 6, why does wf2 show a waveform if it is not explicitly connected to gain g0?

- Attached: [BespokeSynth_issue1638.bsk.txt](https://github.com/user-attachments/files/16930412/BespokeSynth_issue1648.bsk.txt)

**Comment by NoxyNixie** [comment]
I don't see an issue: 
![image](https://github.com/user-attachments/assets/f7527147-9aff-4257-9ef6-f93763fddaa1)

Are you using the latest nightly build?

**Comment by NoxyNixie** [comment]
With regards to everything else you've said I'm not sure I follow any of it. For some reason I have a hard time understanding what you mean and feel like this discussion is more suited for [Discord](https://discord.gg/QUvh5TJ).

**Comment by westurner** [comment]
How dismissive, disrespectful and offensive!  Now I'm not inclined to
further contribute.

FWICS from your screenshot of nightly,  waveformviewer does not require an
output to be connected in order to display the waveform but used to.

Eq does still require an output to be connected in order to display the
waveform.

So, "eq doesn't show waveform unless an output is connected"

Does require an output to operate:

- eq

Does not require an output to operate:

- waveformviewer

Thanks for your time with this. I'm now out of time for this hobby project.

**Comment by NoxyNixie** [comment]
> How dismissive, disrespectful and offensive!

What is dismissive, disrespectful and offensive? As far as I'm concerned I've been civil all throughout this issue. My lack of understanding does not imply offence, if you are offended by my lack of understanding I unfortunately can't help that. This is why I suggested [Discord](https://discord.gg/QUvh5TJ) as this is a place for more real-time communication which allows for finer grained discussion and clarification of points.

> Now I'm not inclined to further contribute.

That is unfortunate you feel that way.

> FWICS from your screenshot of nightly, waveformviewer does not require an output to be connected in order to display the waveform but used to.

Indeed, in the nightly neither `spectrum` nor `waveformviewer` require an output (added in b365387).

> Eq does still require an output to be connected in order to display the waveform.

Correct. This won't be changed because the `eq` module is a audio processing module that changes the audio while the `spectrum`, `waveformviewer` and `lissajous` only pass the audio along so in those module one can cheat and pretend to have an audio buffer. In the `eq` module this is different.

> Thanks for your time with this. I'm now out of time for this hobby project.

You're welcome. I never intended any offense and if you perceived some I'm sorry.
