### ISSUE TITLE
Group Control Blocks sometimes don't save correctly

### ISSUE THREAD

**Issue by lapraswastaken** [BespokeSynth/BespokeSynth#164]
After having saved, sometimes group control blocks will mess up and do this thing where the output is coming out of the block instead of from the block's dots (if that makes sense). I'm on Windows 10 and I'm running the 1.0.0 version.

Here's an image of a group control that got messed up.

![image](https://user-images.githubusercontent.com/63134341/133846184-b5bfe82c-a333-4c11-b418-029cfd11a680.png)

Here's an image of a group control that is doing what it's meant to.

![image](https://user-images.githubusercontent.com/63134341/133846372-fdd8a3d9-6614-462b-a29d-1ec167f30bd3.png)

**Comment by Gate88** [comment]
yep, same issue here. and it can get tricky because if you delete the broken groups in the wrong way it can corrupt your save file! i had to disconnect things in steps and save and reload to a couple different files to avoid corrupting my main file.

here's a reliable way to reproduce the bug:
- recreate the top layout
- save file
- load file
- file will now look like bottom layout (and will not perform correctly)

![image](https://user-images.githubusercontent.com/5875270/134361275-84cf5103-6569-41d1-ab8c-fed6a5c1ee75.png)

**Comment by polerin** [comment]
I've run into this as well.

**Comment by puddlesofun** [comment]
I've had the same issue pretty consistently (using windows).
My kludgy fix in the meantime is if you copy the group controls (just highlight them and hold alt), the copies will have the outputs working correctly.
Of course, it's pretty annoying having to do that and then delete the originals every time you open your project.

**Comment by geppettodivacin** [comment]
I just confirmed this issue in 1.1.0 with about the simplest patch possible. See the before and after below.

![image](https://user-images.githubusercontent.com/3942222/142799485-a3515bee-5c5c-4da6-a5f4-216e41e1654e.png) ![image](https://user-images.githubusercontent.com/3942222/142799515-31d886a0-5073-4ebd-a96d-51c92589ae2c.png)

The connections _are_ correctly saved in the layout json as `uicontrols`:

```json
{
   "modules" : 
   [
      {
         "name" : "groupcontrol",
         "position" : 
         [
            754.0,
            426.0
         ],
         "type" : "groupcontrol",
         "uicontrols" : 
         [
            "notecreator~enabled"
         ]
      },
      {
         "name" : "notecreator",
         "position" : 
         [
            764.0,
            584.0
         ],
         "target" : "",
         "type" : "notecreator",
         "voice index" : -1
      },
      {
         "name" : "scale",
         "position" : 
         [
            158.0,
            95.0
         ],
         "type" : "scale"
      },
      {
         "name" : "transport",
         "position" : 
         [
            14.0,
            95.0
         ],
         "type" : "transport"
      }
   ],
   "zoomlocations" : []
}
```

Reading through the source code, around https://github.com/BespokeSynth/BespokeSynth/blob/021507c4d04987fe6fb523085cac78a6dbe65212/Source/GroupControl.cpp#L120, I don't see any glaring issues with the loading code. I'm not quite as sure about the binary part of the bsk format, so it might be doing something odd after the fact? Or maybe it's an odd order-of-operations thing and the destinations don't exist when the connections are being made?

EDIT: Moved the images side-by-side for easier comparison.

**Comment by geppettodivacin** [comment]
Two other important things of note:
1. It's not just a graphical glitch. The enable checkbox does nothing with cables connected like this.
2. I can confirm @puddlesofun 's hack of making a copy of the groupcontrol nodes makes it properly, so the data is even correctly stored within the node? At least enough to make a copy.

**Comment by sbungartz** [comment]
I have been getting the same behavior with 1.1.0 (and also 1.0.0 before).
Just wanted to share another workaround that I found, that does not require fiddling around after loading a save state:

You can use a `macroslider` instead of `groupcontrol`.
Instead of binding to "group enabled", bind to "input" of the macroslider, and then connect the outputs of the macroslider to the toggles that should be controlled by that group. Since the toggles are enabled for values > 0.5 and disabled for < 0.5 it works just the same.
Macroslider seems to be persisted correctly.
The number of slots can be increased in the arrow-menu.
Only downside is that it takes up more space.

**Comment by awwbees** [comment]
should be all set now, sorry for the delay on this one! I rarely use `groupcontrol` for some reason, so I kept forgetting to fix this

**Comment by puddlesofun** [comment]
Thanks! Love your work.
