### ISSUE TITLE
Savestate has a gap in buffer of `seaofgrain`

### ISSUE THREAD

**Issue by merkys** [BespokeSynth/BespokeSynth#1704]
## Describe the bug

I made a savestate [2024-07-30_18-34.bsk](https://github.com/user-attachments/files/17791843/2024-07-30_18-34.bsk.tar.gz) using BespokeSynth v1.1.0 and cannot open it correctly with post-v1.2.1. The issue is a gap in the buffer of `seaofgrain`. When I made it with v1.1.0, the buffer was a contiguous recording, but now with post-v1.2.1 there is a gap in it.

## Build info

Savestate was made on BespokeSynth v1.1.0. I tried loading it on both b4674fce and 9839f5b0 + #1690, but both of them show gaps in buffer.

**Comment by NoxyNixie** [comment]
I suspect this is related to samplerates and/or buffersize. You likely recorded that seaofgrain buffer in a lower samplerate and/or buffersize than you are using now.

**Comment by merkys** [comment]
Indeed the samplerate (was 48k) and/or buffersize (was 256) are different.

What can I do now to salvage my buffers? I can open them with my old BespokeSynth install and try to store buffer contents to external files, but this will take considerable time as I will have to rebuild my savestates from scratch.

I recall you saying that older savestates lack buffer parameters such as aforementioned samplerate and buffersize. Are they stored in the newer savestates? If so, maybe I can manipulate the savestates (i.e., by some sort of savestate migration tool) to put this information in?

**Comment by NoxyNixie** [comment]
I believe they should be save in newer savestates however many modules don't account for this changing and thus don't transcode the sample data to the new sample rate. I have been contemplating this or rather the separation of sample data and modules so that one can load just one sample and use it in different modules without duplicating the data (unless specifically desired). This could be a new sample module with associated sample cables. Anyway the details aren't relevant here what this will do is likely fix samplerate transcoding because only one place will deal with sample data. I'm not sure yet how to handle specialized sample buffers like in the `delay` module. I'm also not sure yet when or how to do all this yet.

**Comment by awwbees** [comment]
this is a bug that would occur in the following scenario:
1. you open a project with bespoke set to sample rate [x]
2. you use the "record" feature on a `seaofgrain` module, and save the project
3. you set bespoke to sample rate [y]
4. you open the project at the new sample rate

the fix for this involved adding some additional save data to track which sample rate the `seaofgrain`'s buffer was saved at. to migrate your old projects that have this issue and fix these gaps:
1. download the latest nightly build
5. set bespoke to a 44100 sample rate (which seems to be the sample rate you initially saved the provided project at)
6. open a project exhibiting this issue
7. save it

after doing this, the newly saved project will be able to be successfully opened at any sample rate. as an example, here is a resaved version of the savestate you attached: [gh1704_resave.bsk.zip](https://github.com/user-attachments/files/18017942/gh1704_resave.bsk.zip)
