### ISSUE TITLE
Window size of a VST gets larger

### ISSUE THREAD

**Issue by jandojando** [BespokeSynth/BespokeSynth#192]
With some VST's, for example Valhalla Delay, the window size gets larger every time I open it. Up until a point where I can't resize it anymore, because the resize area is out of view.

I'm running Windows 10.

**Comment by NoxyNixie** [comment]
I am unable to reproduce this effect with any of the VST's that I have in the latest Nightly build of Bespoke.

I unfortunately don't have the mentioned Valhalla Delay but all other Valhalla VST's work fine.

If this problem is still occurring please feel free to report back on this issue and I'll reopen it.
