### ISSUE TITLE
some bugs & suggestions

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#2]
Hello ,
Congrats and thanks for this release, 
some bug i've notice:
 - for the MIDI circle sequencer, i suppose there's missing note off, cause after first sequence no note are send, maybe not all VST need this , but at least some?
so i found a workaround with adding a curve looper to the range of a note wrap  ( see attachement)
 - When i reload this patch, the point in the circle seq are not present anymore
 - a suggestion, space bar to active/stop audio engine could be cool ?

Thanks for reading

( btw, don't know if you use social networks, but I've share your work on our Facebook group about [experimental tool ](https://www.facebook.com/groups/2147926972195324/?multi_permalinks=2610685365919480&notif_id=1580459378850232&notif_t=group_highlights)

![bug midi](https://user-images.githubusercontent.com/13808201/73534890-935ace00-4422-11ea-8704-6e169fed06c0.jpg)

**Comment by awwbees** [comment]
thank you for taking the time to check out bespoke!

yes, there are indeed a number of bugs, particularly around reloading save states not properly restoring everything. my cop-out answer for now is "embrace the ephemerality of your patches, because maybe they won't come back when you reload them!"

I have only used the circlesequencer in conjunction with my drumplayer module, which doesn't care about note-offs, so you're right on the money there. a better way for you to hack the circlesequencer to do note-offs would be to route it into the notesustain module, which will do a note-off after a specified length of time.

I can't seem to access that link on facebook, perhaps the group is private.

**Comment by nay-seven** [comment]
i agree with your ephemerality philosophy ;-)
Thanks for the notesustain tips, works fine.
And you're right about the group, i can invite you if needed ;-)

**Comment by awwbees** [comment]
sure thing! I don't use facebook much, but I will take a peek in that group. my facebook account is facebook.com/awwbees for the invite

**Comment by nay-seven** [comment]
i've send you an invitation as friend cause i can't invite you in the group if you're not, 
facebook.....;-)
or i suppose you can use the "ask to join the groupe" ?

**Comment by asmw** [comment]
@nay-seven are all of these still issues? If so, could you please open individual issues for bugs + feature wishes, that is easier to track

**Comment by awwbees** [comment]
ah yes I think these are all fixed now
