### ISSUE TITLE
Routing incorrectly recalled in Looper modules after saving project

### ISSUE THREAD

**Issue by NikalMight** [BespokeSynth/BespokeSynth#201]
I have a looper recorder feeding two loopers. Prior to saving, they were both connected to the main gain feeding the outputs. After saving, the first looper's output is connected to the second looper's input and neither are connected to the gain. I tried reconnecting the outputs to the gain and resaved, but the problem reoccurred, so it is reproducible. If I disconnect the looper recorder and resave, the problem no longer occurs, so I assume that's where the bug is.

![Bespoke routing bug](https://user-images.githubusercontent.com/33601212/133939360-069ece13-6754-49a8-b093-31c66cf8f178.png)
.

**Comment by awwbees** [comment]
ah, sorry, I think this is more a problem of an unintuitive interface: you shouldn't feed a looperrecorder into a looper, you should instead have the looperrecorder feeding straight through to the gain you mentioned. the audio gets sent to the loopers "magically" via those gray cables. there is an example save file that shows how a looperrecorder should be configured

so, that should fix your issue, but it also sounds like there is a bug with that wackiness that happens when you don't patch the looperrecorder as expected
