### ISSUE TITLE
Opening states on macOS almost crashes Bespoke

### ISSUE THREAD

**Issue by kenokenobingo** [BespokeSynth/BespokeSynth#21]
When opening a state (`.bsk` file), Bespoke crashes or almost crashes. Sometimes there’s also a humming noise on the audio signal.

OS: macOS 10.15.6

**Comment by awwbees** [comment]
this does not occur for me. can you post an example .bsk file that crashes for you, so I can try to reproduce it and find more info?

**Comment by kenokenobingo** [comment]
For example, this file: https://transfer.sh/zqV62/2020-08-15_14-42.bsk. (GitHub gist wasn’t working unfortunately because the file is too large.)

**Comment by awwbees** [comment]
hmm, unfortunately this file will not download for me, I don't seem to be able to access transfer.sh

if possible, you could email it to me at my username @gmail.com

**Comment by awwbees** [comment]
thank you, I received the .bsk that you sent! it also crashes for me when I load it. it appears to be crashing when loading the "sampler" module, so I likely have some bug in the savestate for sampler modules. I can't recreate a crashing save file locally, so it must be caused by something more subtle, I will keep digging to figure out what's going on. if I short-circuit the sampler loading in code, the rest of your .bsk file opens fine.

in the meantime: can you still get the crash if you don't use a "sampler" module? if not, I would advise avoiding the sampler module for now.

**Comment by kenokenobingo** [comment]
Thank you! Yes, it also crashes when I try to open the patch without a sampler module.

**Comment by awwbees** [comment]
hmm! so to test the very basics of saving: if you just load straight into bespoke and don't add any modules, then save state, then load that basic state, does it crash? if it does, can you send that .bsk to me?

**Comment by kenokenobingo** [comment]
The basic state loads very quickly and without problems.

**Comment by awwbees** [comment]
gotcha. so, it sounds like there must be certain modules that don't serialize correctly, either due to a bug that effects everybody, or an issue specific to your machine's configuration. if you have the time, creating the simplest possible patch that still crashes when you try to load it would be helpful to narrow down the issue.

**Comment by cosmikwolf** [comment]
on loading the example__scripting.bsk file, on bespoke version 1.0.0, on an M1 Apple Sillicon Mac Mini running OS 11.3, Bespoke plays a tiny sound, and then exits. I don't get an OS X "This app unexpectedly quit" notification like I usually do.

**Comment by awwbees** [comment]
stale issue, let's close this!
