### ISSUE TITLE
Crash/Exit while scanning for VSTs (Windows 10)

### ISSUE THREAD

**Issue by bobvodka** [BespokeSynth/BespokeSynth#223]
While scanning for new VSTs Bespoke crashes/exits with no crash log or other output.

I've a large number of VSTs (which all work/scan fine with Bitwig 4, my normal DAW) so some kind of logging would let me at least try to narrow the problem down but there doesn't seem to be any performed? (and there is no log file generated on exit)

The VSTs installed are a mixture of 32bit, 64bit an VST2 and VST3 with some duplication between them (because I was bad at installing some, and other give you no choice).

Reproduction : 
1) Open Bespoke
2) Click on 'rescan VSTs...'
3) Wait
4) Window show 'not responding'
5) After a period of time the application just exits

**Comment by rgreset** [comment]
Same issue but on my iMac (Catalina 10.15.7). I have tried to to scan only VST2 but it didn't help.

**Comment by ChapelHeel66** [comment]
I was in the same position as the OP, including some jbridged plugins.  There were two jbridged plugins that Bespoke didn't like, and I don't really use them anymore, so I deleted those, but still got the crashes.

So I pared down my paths to the "must haves" and got it to work.  I cannot be 100% sure, but I think it may not like the Waves plugins if you have them installed in Program Files (x86)\Waves (which is where Waves put them at some point)...or it may be that Bespoke does not like anything in a Program Files (x86) directory.  

Anyway, I thought I would mention this so others can try it, because it is a lot less drastic than the workaround mentioned in #112.

**Comment by PPiinngg** [comment]
Same issue here.

**Comment by KottV** [comment]
Scanning the ~pile of garbage~ huge collection of mixed versions plugins with Bespoke is not a good idea yet.
For now it's recommended to provide separate dir(s) with actual plugins/symlinks.

**Comment by awwbees** [comment]
fixed with new scanning process in #421
