### ISSUE TITLE
Value setter targetting GUI buttons misbehaves when split with a macro slider

### ISSUE THREAD

**Issue by oneero** [BespokeSynth/BespokeSynth#234]
If I have a pulser running via a value setter to a GUI button everything seems to works as I expect. If I then want to split this modulation signal by shift dragging the output (adding a macro slider in the process), the behaviour seems to change completely.

## Expected Behavior
I would expect the macro slider to trigger the target GUI button in the same way as the value setter does on its own.

## Current Behavior
The macro slider seems to be triggering the button constantly at a high frequency.

## Steps to Reproduce
https://user-images.githubusercontent.com/3067956/134336769-90c854ec-1e77-45d1-badc-52460bb51431.mp4

Slightly unsure if I am simply using these modules wrong or if this is a bug, but I do think the behaviour is at least unintuitive. Users can avoid this issue by duplicating the value setter as many times as is needed, but it feels wrong when there is an existing convention for splitting signals.

**Comment by NoxyNixie** [comment]
A recent change made it possible to duplicate "value setter" cables (these are a special brand of modulation cable and have a slight darker tint to their color) without having a `macroslider` module inserted into the cable.

This should resolve the issue of not being able to properly split these types of cables (`curvelooper` also uses this special cable type).

Beyond that the behavior of a `valuesetter` into a `macroslider` is kind of expected as shown above since the button is now forcibly held pressed by the `macroslider`. You can work around that by using a `pulsedelayer` into another `valuesetter` with value `0`.

If you think this is still an issue or you don't understand something please don't hesitate to reply here or post a new issue ;)
