### ISSUE TITLE
Created modules spawn outside the current view

### ISSUE THREAD

**Issue by unfa** [BespokeSynth/BespokeSynth#347]
Please see how when I create a module (in thsi case Pocketverbs from AirWindows, but tu was happenign for all modules), the module is created outside of my view and I have to look for it:

https://youtu.be/mh66PG_LeEM?t=4688

I think the modules should be created either undet the mouse cursor or in the middle of the current view if triggered from the top menu.

What do you think?

**Comment by awwbees** [comment]
haha! I was already halfway through watching this video when I came across this github issue. thanks for showing off bespoke!

the module should be appearing at the cursor as you suggest, but it appears that you are hitting some sort of bug, I will investigate.

the intended way that you should be spawning modules is to drag them from the quickspawn list, rather than just clicking, which I think will give you the smoothest experience. but, the "drag" behavior seems to be pretty unintuitive (many people are making this same mistake), so I think I will make the module "stick" to your cursor when you single click it, to make it easier to place where you want.

**Comment by unfa** [comment]
Oh wow, my pleasure :D Thank _you_ for making BespokeSynth and making it open-source!

I see. I must have forgot about the drag'n'drop intended usage when I watched your video about basic tricks (super useful stuff, though I had to re-watch many parts a few times as you've been quite swift with it :D ).

I would expect a single click to place the module below my mouse cursor, or at the location it was when I pressed the key that triggered the menu.

This way I can easily point my mouse at a place on the canvas thinking"I want a module here", then hit a key to bring up the name-letter menu, chooseto confirm and done. Dragging never occured to me, but I guess clicking and dragging would then spawn the module at mouse down position (not at the position where the mouse was when the name leter menu was triggered) and stick the module with the mouse cursor until the mouse button is up?

Seemingly such a simple thing but there's quite a ew decisions to make abotu the logic it should follow.

**Comment by awwbees** [comment]
I think there's probably an issue where the module gets positioned when you drag the mouse at all, but you're a precise enough clicker that you mouse-up without moving even a pixel, so the module gets positioned in some other weird spot. I must be a sloppier clicker, so I "drag" a pixel or two when I click, and never noticed this bug.

I will play around with a few options for "click without dragging" and see which one feels best. your proposal sounds like it might be a nice one.
