### ISSUE TITLE
Resetting Timeline to Zero, first note is not played

### ISSUE THREAD

**Issue by PastMoments** [BespokeSynth/BespokeSynth#361]
Resetting timeline to zero through the transport module causes all notes set to time 0 to not be played.

To reproduce:
1. Create note canvas, attached to any synth and output.
2. Assign a note to the very start of the canvas.
3. Press "reset" on the transport module

A note should play, but it does not. The note does play as the canvas loops around, but not when the timeline is reset.

**Comment by asmw** [comment]
I cannot reproduce this with the current main branch.

I did:
- create a notecanvas
- added a single note using shift click
- wire up a synth

Hitting the transport reset immediatly produces the note.

Technically the reset sets the transport to a very small negative value (`0.001f`) so I guess the OS/hardware could somehow play a part in this issue?

What OS/architecture are you on?

**Comment by asmw** [comment]
This bsk (github required me to zip it) automates the reset and produces a repeating sound for me
[reset_issue_test.zip](https://github.com/BespokeSynth/BespokeSynth/files/7395198/reset_issue_test.zip)

The only way I could produce the problem is when I nudge the note into the _negative space_ before the canvas, i.e. by slightly dragging it to the left using alt-drag, which would make the note technically start before the canvas. But that also does no produce a sound for a timeline wraparound

**Comment by spectromas** [comment]
I'm experiencing this a well with the drum sequencer, it always starts on the 2nd note. I'm using a build from Oct 26 so I think it should have that pull request. Is this a separate issue?

**Comment by asmw** [comment]
@spectromas indeed, the issue also exists with the drumplayer and the increase is not enough there.
Could you file a new issue for that?
I don't think fudging the rewind value again and again is the correct solution

**Comment by asmw** [comment]
FYI: for the drumplayer on my system (Ubuntu, using pulseaudio) the issue goes away with a rewind amount of -0.07f
