### ISSUE TITLE
Missing json files?

### ISSUE THREAD

**Issue by djdeath** [BespokeSynth/BespokeSynth#39]
I'm getting some crashes that seems to be related to missing files : 

```
868.221: Could not load file /home/djdeath/src/BespokeSynth/Builds/MacOSX/build/Release/data/controllers/osccontroller.json
```

**Comment by KottV** [comment]
I got such message in log too and when I chose my xkey midikeys:
```
0.555667: Loading layout: /home/kv/.config/BespokeSynth/data/layouts/blank.json
11.7263: Could not load file /home/kv/.config/BespokeSynth/data/controllers/.json
15.9583: Could not load file /home/kv/.config/BespokeSynth/data/controllers/osccontroller.json
103.276: Could not load file /home/kv/.config/BespokeSynth/data/controllers/Xkey MIDI 1.json
```
but no crashes yet
could you provide steps for reproduce?

**Comment by awwbees** [comment]
I think whatever crash you're getting is probably unrelated to that output. That print spam shows up because it's trying to look for the name of the selected controller to create a layout for it. For example, you can create an `Xkey MIDI 1.json` to have a custom layout for that controller. If it can't find that file, it just uses the default layout.

I should probably clean that up to not print out an error message, though, and handle it more gracefully, since failure is often "expected" in that case.

This doesn't explain any crash you're getting, it would be good to find out more information about that.

**Comment by djdeath** [comment]
Okay, closing for now. Thanks for the explanation.
