### ISSUE TITLE
Cursor position offset on macOS?

### ISSUE THREAD

**Issue by mstange** [BespokeSynth/BespokeSynth#545]
I keep misclicking in Bespoke. When I want to drag windows, I often instead do a lasso selection above the window. And in the sequencers I often hit the cell above the one I want to click.

Is the mouse cursor position offset to the top left by a few pixels? I'm on a HiDPI display.

**Comment by awwbees** [comment]
interesting... there is actually an offset that I put in on mac only, but it was because the cursor positions like this on my own retina display. I will take a look at this again, maybe something changed...

https://github.com/BespokeSynth/BespokeSynth/blob/24b7f8ee7e95b72c14006cff01fa2c1619e5e3e3/Source/ModularSynth.cpp#L1021

**Comment by awwbees** [comment]
hmm. it's really odd. I just tested and that -4 number is still correct for me, if I change it then everything is offset incorrectly.

**Comment by mstange** [comment]
Hmm, interesting. Does your expectation of the "correct" mouse position agree with the position that apps like Pixie or Digital Color Meter show? Unlike Windows, on macOS the hotspot of the mouse cursor is not at the tip of the arrow, it's slightly offset towards the middle of the arrow shape.

**Comment by awwbees** [comment]
really??? man, that's so bizarre, I've been both a windows and mac user for the past decade+ and this has never popped up on my radar. maybe I'll make a user option for mouse pixel offset? when I get rid of my offset, bespoke feels super broken to me on mac.

**Comment by mstange** [comment]
thanks
