### ISSUE TITLE
Adding a script module crashes Bespoke Synth on Windows 10

### ISSUE THREAD

**Issue by dospunk** [BespokeSynth/BespokeSynth#61]
Title says it all, trying to select a script module immediately exits Bespoke

**Comment by dospunk** [comment]
Here's the error message:

```
 Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\MyUser\\Desktop\\Bespoke Synth\\BespokeSynth.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\Users\\MyUser\\Desktop\\Bespoke Synth\\BespokeSynth.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\MyUser\\Desktop\\Bespoke Synth\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Users\\MyUser\\Desktop\\Bespoke Synth',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000760 (most recent call first):
<no Python frame>
```

**Comment by awwbees** [comment]
I should definitely make this not crash, and give a good error message, but I'd guess this might be caused by an issue with your python install. do you have python installed? to confirm for you, the script module works for me in both windows 10 and macOS.

**Comment by dospunk** [comment]
Yes, I have Python 3.9.0 installed

**Comment by awwbees** [comment]
thank you for confirming! these machine config bugs are so tricky to debug/repro. does this workaround fix the crash for you? https://github.com/awwbees/BespokeSynth/issues/31

I still need to figure out the real fix, and why it's only a problem for some users

**Comment by enchilada404** [comment]
Have you made any progress on this?

Would love to see the script module working on windows 10/python 3.9... 🙏

**Comment by awwbees** [comment]
I have not made progress, I'm not yet sure if it's possible to support multiple versions of python simultaneously, and it is not a high priority for me since python 3.8 is functioning fine. have you tried with python 3.8? that should work. here's a much more recent build to try: https://www.dropbox.com/s/5mqkzefw4mubdcx/Bespoke-Windows-20200726.zip?dl=1

is there any specific reason you'd prefer to use python 3.9 over 3.8?

**Comment by dromer** [comment]
The best solution would be to embed python more directly and link to an interpreter statically.

**Comment by j-red** [comment]
I was able to resolve this issue with the workaround from #31 by installing [Python 3.8.10](https://www.python.org/downloads/release/python-3810/) to the default install location and entering `set PYTHONHOME=C:\Users\<your user>\AppData\Local\Programs\Python\Python38` into the Command Prompt. Now scripts work like a charm!

**Comment by prehensile** [comment]
I had the same problem and can confirm that the fix from #31 works.

I've put together a slightly more repeatable / durable solution for now:
- Install Python 3.8 from https://www.python.org/downloads/windows/
-- I chose to install for all users, becauase the idea of having a whole Python install in my user directory feels untidy to me. In reality, it probably doesn't make any difference where you install it.
- Place the attached **.bat** file in your Bespoke Synth install directory, probably **C:\Program Files\BespokeSynth** (rename from **.bat.txt** to **.bat**): [launcher.bat.txt](https://github.com/awwbees/BespokeSynth/files/7189617/launcher.bat.txt)
- You'll probably need to edit the **.bat** file to reflect your Python install location
- Edit the shortcut to Bespoke Synth in your Start Menu (right click -> properties) to point to **launcher.bat** instead of **BespokeSynth.exe** (in the same directory)
- (Optional) Edit the shortcut's icon to use BespokeSynth.exe to get the nice icon back :)

Now your start menu entry sets up the correct PYTHONHOME variable every time!

**Comment by prehensile** [comment]
A suggestion for what might be a low-effort fix in Bespoke itself: a setting in the config menu which would allow the user to set a string for the PYTHONHOME var, which could then hopefully be passed to pybind on init? I had a quick poke at the pybind source to see if there was anything immediately obvious, but I'm not a C++ programmer so it went way over my head.

This suggested fix might be useful on other platforms, too, if folks have system versions of Python installed that aren't 3.8

**Comment by awwbees** [comment]
this is a good suggestion, I will look into it

**Comment by prehensile** [comment]
A slightly more hacky, but would probably work, version of the above would be to set the env var from Bespoke before initing pybind.

**Comment by prehensile** [comment]
Aha! I can't see any obvious way to set PYTHONHOME in pybind, but you _can_ set it by calling `Py_SetPythonHome` directly in the Python C API; there's some example code in this pybind issue here: https://github.com/pybind/pybind11/issues/2369 (which I can see you've already come across, @awwbees). Thanks for the awesome software!

**Comment by yhancik** [comment]
The PYTHONHOME fix works for me too. I'd like to add that if you're using Powershell instead of the old Command Prompt (and I think it's the default on Windows nowadays?), you have to set PYTHONHOME with 
`$Env:PYTHONHOME="C:/path/to/your/python3.8/install"`

**Comment by awwbees** [comment]
should be all set now that bespoke includes its own python
