### ISSUE TITLE
module names shouldn't have to be implicitely unique

### ISSUE THREAD

**Issue by rerry1234** [BespokeSynth/BespokeSynth#640]
in practice, you can have modules with the same name.
but if you do, connections get messed up after reloading a project from a save file.

it seems as if module connections (on project load) are based on module names.
better would be to use module uuids. 
(or names should be checked if they are unique - which would constrain user with naming conventions.)

edit: bespoke 1.0.9992

edit: 
rebuilt bespoke 1.1.0 (Nov 22 2021 23:16:38) - Linux - main 83fbb8b
same.

**Comment by awwbees** [comment]
many things depend upon unique module names, such as scripting, or user-facing midicontroller connections, so uuids would be inappropriate. I will make a change to prevent renaming to an existing name, though

**Comment by rerry1234** [comment]
ok, so that problem has an even bigger context.

> I will make a change to prevent renaming to an existing name, though

nice!

edit:
also, then it would be optimal to go through all the names after renaming an item to keep all the references...

**Comment by awwbees** [comment]
> also, then it would be optimal to go through all the names after renaming an item to keep all the references...

this does happen, other than with scripts (because automatically editing scripts feels incorrect)

**Comment by rerry1234** [comment]
makes sense.
could you scan the scripts and give a warning when there is an expression in there that fits the old (module)-name?
so users would be aware.
i mean- users who script by themselves should be considered more experienced, but problems from a situation like this could be hard to find, i guess.

**Comment by rerry1234** [comment]
reference names in "noterouter" module are not being updated on name change of the referenced item.

**Comment by NoxyNixie** [comment]
Unique names are required and various changes have been made to ensure unique names.

To change the architecture to use UUID's will require a backwards compatibility break in the savestates and this is not planned.

It is highly unlikely we will endeavor into making UUID's a thing within Bespoke since there are a lot of far more important and fun features we'd like to implement first before breaking all savestates just for UUID's. Perhaps when the savestate file is redesigned we may include UUID's but this is not planned.
