### ISSUE TITLE
Cannot bind pitchbend on more than one channel....

### ISSUE THREAD

**Issue by sonic-neil** [BespokeSynth/BespokeSynth#720]
## Describe the bug

Bind channel 1 pitchbend.
Try to bind channel 2 pitchbend in the same midiController it will fail.

## Build info
1.1.0

## Steps To Reproduce

Just try it!

[example 1](https://streamable.com/qqdzod)
[example 2](https://streamable.com/njq8ja)

## Expected vs. actual behavior

Expect to be able to bind all 16 channels of pitchbend.
Fails on second binding.

**Comment by NoxyNixie** [comment]
You can have multiple `midicontroller`s all acting on different channels using the `channelfilter` triangle menu setting:

![image](https://github.com/user-attachments/assets/ec221a9d-5f5b-4b18-aecb-2e974753f0c8)

Your examples also no longer work so I can't really see what exactly you meant.

For now I'm closing this issue since I'm not sure if something is needed to be changed here. If you have more information or more details on what you expect (and how) then feel free to respond to this issue or create a new one.
