### ISSUE TITLE
Crash on Looper "W" button

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#76]
Hi, (it's me again)

I started to learn how to use the looper and looprecorder, but accidentally found this issue.
Before hopefully you fix this, Ryan, could you provide some description about these modules, and what all these controls for?
For example, I want to use it as simple guitar loop pedal. BespokeSynth is very good for guitar effects host.

Add looper module.
Add some synth (fmsynth or karplus).
Connect synth to the looper, connect looper to the output (gain).
Press "w" button twice.

Windows also affected.

**Comment by awwbees** [comment]
this crash is now fixed in 3b92f6f58f9426f64f6a4b6690e7c27458abc044

I'm in the process of writing tooltips now for all of the modules' controls, you can access it by clicking the "?" button in the upper left corner and enabling "show tooltips". this will show a description of each control you hover over.

unfortunately, I haven't yet written tooltips for the looper and looperrecorder modules, but I am in the process of doing that now and they should be ready fairly soon. years ago, I used bespoke extensively as a looper, so those modules are packed fairly densely with features, but much of it is pretty obscure. hopefully the tooltips will adequately explain their usage.

**Comment by KottV** [comment]
Thank you a lot!

Yeah, I saw tooltips.
I think about translate them to Russian, not sure if it will be useful for users, but I'll learn them during that task at least.
