### ISSUE TITLE
Best way to update ?

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#8]
Hello,
After downloading last version, i try to load state from old version, this crash Beskope, so i copy my "savestate" folder in the new data folder, some works ,some crash.
Is there others things to copy to use old state ?
thanks

**Comment by awwbees** [comment]
hmm, I don't think I made any explicit changes to serialization in between builds, so that's curious that it crashes now. if you attach a .bsk that loaded in the old build and no longer loads in the new build, I can take a look to see what might have changed

**Comment by nay-seven** [comment]
Here one:
[circle with random++2.bsk.zip](https://github.com/awwbees/BespokeSynth/files/4225531/circle.with.random%2B%2B2.bsk.zip)

**Comment by awwbees** [comment]
it's failing to load for me, but it looks like it's happening because I'm missing the VSTs that you have. I just added an update in 3f52f96 to handle this failure more gracefully, as shown in the attached image. the state will still load, just with unloaded VSTs.

in the meantime, I think you could likely resolve this if you open Bespoke, click the "vst plugins" dropdown on the top bar, click "rescan vsts...", then load your state again. scanning for VSTs will take a while and will make Bespoke appear temporarily frozen, but you only need to do it once and it will save the VST list for the future. in 87c1cd7 I changed how VST loading works, which is what I suspect caused this issue for you.

let me know if rescanning VSTs doesn't resolve your issue.

<img width="1692" alt="Screen Shot 2020-02-19 at 10 07 28 PM" src="https://user-images.githubusercontent.com/839239/74897310-a814ec80-5364-11ea-8f2f-455f9b120079.png">

**Comment by nay-seven** [comment]
Hello, thanks but no, this don't resolve the issue, ( but maybe not a big deal , i can also rebuild these patches...)
Some other thing i notice with this last version:
At first i think the defaut blank .json is not recreated, so i need to rebuild  gain/splitter/outputs 1 & 2
but even this way i don't have sound.
so i test with an old userfrefs.json and it works
so i finally delete these 2 lines:
`   "audio_output_device" : "auto",
   "audio_input_device" : "auto",`
works, but only in mono ?
( for info i see signal activity on both wires and my outputs 2 is set to 2
And finally i dezoom the main interface and i realize the gain/splitter/outputs 1 & 2 modules was here but hidden in the low low part and that's why it don't work... ;-)

**Comment by nay-seven** [comment]
but you're right about Vst's cause if i open an old patch without any vst's it works
