### ISSUE TITLE
Presets module bug with blends parameter

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#806]
Hello,
When using blends parameter in the presets module other than 0, Bespoke cut some links between audio modules and bug

## Build info:
bespoke NIGHTLY 1.1.0 (Mar 30 2022 04:21:18) - Mac OSX 10.14.6 - HEAD e2484f6

## Steps To Reproduce

load the example attached, change presets, now use a blends of 80 for example, here preset 3 reproduce the bug
link between audio modules are broken, see picture

<img width="616" alt="Capture d’écran 2022-04-04 à 19 03 39" src="https://user-images.githubusercontent.com/13808201/161595075-6db41c56-a21c-4776-b006-003707a7c6e6.png">

[test bug presets.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/8411713/test.bug.presets.bsk.zip)

**Comment by NoxyNixie** [comment]
The audio links becoming visually "disconnected" is an indication of `NaN` values being propagated. I believe this is an issue with the `oscillator` module rather than the `presets` module.

I've had this behavior pop up once in a while too but haven't been able to pinpoint yet what values or sliders can cause these issues.

**Comment by nay-seven** [comment]
hello,
you must be right, i have test the same patch with FM synth, Drumsynth ( randomize this one crash sometimes but not the same way) and some vst and blend looks ok
