### ISSUE TITLE
One of my savestate not loading anymore.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#83]
Hi,

I really hope to recover one of my savestate. Looks like it became broken since changes in drumsynth, but i cannot load it with older versions too.
Could you give me some advice how to narrow a problem? I can share this .bsk (here or e-mail).

**Comment by awwbees** [comment]
if you can share the .bsk, that would be helpful. I try to maintain backward compatibility, but sometimes I miss stuff

**Comment by KottV** [comment]
[canopener.zip](https://github.com/awwbees/BespokeSynth/files/6281904/canopener.zip)
here it is

**Comment by awwbees** [comment]
here is a version of the file that loads
[canopener_fixed.zip](https://github.com/awwbees/BespokeSynth/files/6291067/canopener_fixed.zip)

it seems that somehow you got the json to save with the wrong number localization format, which I thought was an issue I had fixed... strange. this is the same issue as #4. did something in your setup recently change that might have caused this to suddenly happen, like updates to your system's language/locale config? or maybe somehow you accidentally made a savestate in a very old build of bespoke (from prior to feb 2020). you can see that the json portion of the bsk saved with commas as the decimal separator, rather than periods, which confuses the json parser: 
<img width="432" alt="Screen Shot 2021-04-10 at 10 39 41 PM" src="https://user-images.githubusercontent.com/839239/114290432-bda81280-9a4d-11eb-9b9b-aa2301e059a3.png">

**Comment by KottV** [comment]
Great that issue is so simple!
And I can't remember what had happened with this savestate. Most possible that I've saved it with old Bespokesynth.

Thank you!
