### ISSUE TITLE
triggering the pulse sequencer

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#88]
Hi,

Pulse sequencer initially just pulses. But it's possible to feed it with other pulser (what is it for?), after that pulse sequncer steps only with triggering by parent pulser.
Also it has maximum 32 steps but 16 outputs only.
![изображение](https://user-images.githubusercontent.com/4686351/119260878-2ae7bf80-bc18-11eb-9b5d-36d9a0846375.png)

**Comment by awwbees** [comment]
I updated pulsesequencer to have enough cables to match the 32-step max in 349676a3e9730aca086fb81d389b438b31d8274e

the behavior to allow sequences to be pulsed is intentional, but perhaps not intuitive. the design is: sequencers can automatically advance themselves, like you'd expect, but can also be driven by external sources (other pulses, or notes to specify steps, or the notecounter object). once a sequencer has received a pulse or note, it ceases advancing by itself automatically, and instead only advances when it receives a pulse or note, so it can be controlled manually.

using sequencers in this way allows for more advanced sequencing behavior: you can use a pulser with a pulsechance to make a pulsesequencer advance through its sequence in a randomized way, for example.

additionally some types of sequencers take a note input, which allows you to specify certain steps to advance to. this setup, for example, has the second sequencer playing through the first three steps, then resetting and playing through the first five steps, and looping (as specified by the sequence in the first sequencer)
<img width="687" alt="Screen Shot 2021-05-31 at 7 58 15 PM" src="https://user-images.githubusercontent.com/839239/120249999-ac5bd500-c24a-11eb-9208-5ac6d3a05f05.png">

**Comment by KottV** [comment]
I see, looks like an article for a FAQ.
