### ISSUE TITLE
startup error with audio device

### ISSUE THREAD

**Issue by davephillips** [BespokeSynth/BespokeSynth#9]
I have an odd problem with Bespoke now. The laptop is up to date and running fine, Bespoke works without troubles there. On the desktop box I get this when I start the program:

`error initializing audio device: device didn't start`

Both systems are set up with Jack via the PulseAudio sink, which doesn't seem to cause any issues elsewhere. Will the userprefs.json file accept anything other than "auto" for its audio device ?

**Comment by awwbees** [comment]
with "auto", bespoke will use the OS's default audio output/input devices. if you want to choose specific devices, you can use their names there instead of "auto". for example, on a mac you can specify "Built-In Output" to force it to use the speakers instead of a connected audio interface.

the "device didn't start" error text is coming from inside JUCE, so it seems like JUCE is unhappy with your audio devices, for some reason. that is unfortunately a very generic error message, compared to the more specific ones JUCE often gives ("unsupported sample rate", etc)

**Comment by davephillips** [comment]
@awwbees Thanks, I'll keep trying things, will post a report when I get it resolved.

**Comment by davephillips** [comment]
@awwbees Okay, I resolved the issue simply by plugging in my external USB audio/MIDI device. The device itself doesn't matter, but apparently it makes a difference to how JUCE determines what audio devices exist and in what order they get listed.

**Comment by awwbees** [comment]
maybe when there's an error message I could pop up helpful info like "here are the available sample rates, here are the available audio devices", etc, to make troubleshooting easier.
