### ISSUE TITLE
Release cadence?

### ISSUE THREAD

**Issue by brylie** [BespokeSynth/BespokeSynth#912]
## Summary

It would be cool if there were more frequent releases, since there seem to be many changes and improvements in this project

**Comment by NoxyNixie** [comment]
Currently there is a large list of fixes and changes indeed. However there are still a couple of things that need to be worked on and tested before 1.2 is ready for release.

It is also important to know that @awwbees has limited time and does not want this project to turn into yet another job. So for that reason there is no public todo list or planned release dates. @awwbees wants to keep this project as a fun hobby project.

**Comment by awwbees** [comment]
that being said, I have been meaning to do a 1.2.0 release for quite some time! it has been difficult to determine when to stop adding features and wrap up a release, and I have definitely gone for too long at this point.

the nightly build (https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly) has remained quite stable, so that is a good place to head if you are eager for the latest features, but it would be nice to wrap things up and make an official stable 1.2.0 release.

**Comment by dvzrv** [comment]
Packaging this project for Arch Linux, I'd also be happy to see a release, as 1.1.0 seems incompatible with juce >= 7.0.0.
