### ISSUE TITLE
Add search key/hotkey

### ISSUE THREAD

**Issue by ThePython10110** [BespokeSynth/BespokeSynth#920]
## Summary
It would be great if Bespoke had a search key or hotkey. Insert seems logical. You could just press the key, then type the name of the module/plugin without needing to hold down keys (and no character limit), then click on the module or click anywhere else to cancel.

### Motivation
I have a lot of VST plugins, so my searches need to be more specific than one letter. I don't like having to holding down 3 keys while also clicking on the right plugin.

**Comment by KottV** [comment]
What version of Bespoke? Nightly has a cool new search ability.

**Comment by ThePython10110** [comment]
Oh... I guess I haven't tried the nightly builds yet.

**Comment by NoxyNixie** [comment]
In the Nightly build you can search using the new module list that can be activated by either `right-click` on an empty space or a "mouseless" method using `shift shift` (that is double tap a shift key).

The menu that opens can be typed in to find specific modules and navigated with the cursor keys and finally selected with `enter` (If you hit `enter` again it will also place the module down instead of sticking to the mouse pointer).
