### ISSUE TITLE
Feedback module is initialized with delay set to minimum of 23.2426

### ISSUE THREAD

**Issue by crshrprt** [BespokeSynth/BespokeSynth#927]
## Describe the bug

Feedback module is initialized with delay set to minimum of 23.2426 and maximum of 20.

## Build info

Linux
Debian Sid
Latest Nightly (https://github.com/BespokeSynth/BespokeSynth/commit/aa6f2b9acf991603c467393b3fea7340e51fc26b)

## Steps To Reproduce

Adding a feedback module
![2022-09-30_11 44 57 786](https://user-images.githubusercontent.com/114294020/193243776-80351e9d-92ae-4594-8638-ed83a721959b.png)

## Expected vs. actual behavior

Feedback module should have initial minimum delay value of 1.

**Comment by awwbees** [comment]
due to the way bespoke operates, the minimum delay amount of `feedback` is determined by your buffer size, it can't do sub-buffer feedback. it seems like you must be running with a fairly large buffer size (1024 samples at a 44100 sample rate), if you lower your buffer size then you will be able to achieve lower `feedback` delay times.

it is definitely weird behavior that in the case where you have a large buffer size, the minimum value of the delay slider ends up being higher than the maximum value. I'll have to clean that up.

**Comment by crshrprt** [comment]
Yes, I was running at 1024.  Thanks for the explanation, I wrongly guessed it was post buffer size.
