### ISSUE TITLE
Waveshaper module  glitch disconnecting when there is a division by zero

### ISSUE THREAD

**Issue by crshrprt** [BespokeSynth/BespokeSynth#928]
## Describe the bug

Waveshaper module  glitch disconnecting all the following connected modules when there is a division by zero.

## Build info

Linux
Debian Sid
Latest Nightly (https://github.com/BespokeSynth/BespokeSynth/commit/aa6f2b9acf991603c467393b3fea7340e51fc26b)

## Steps To Reproduce

Enter a waveshaping expression where a division by zero occurs.

Sometimes changing the variable values, ex. to a value different from zero, recover the glitched state, sometimes not.

https://user-images.githubusercontent.com/114294020/193249253-399ce13c-c75a-4593-acd7-0195e613cc21.mp4

## Expected vs. actual behavior

Waveshaper doesn't glitch/disconnect all the following modules when a division by zero occurs.

**Comment by NoxyNixie** [comment]
I'm not sure what the correct behavior here should be or if this is even a bug.

A division by zero is mathematically impossible and thus causes bespoke to propagate `NaN`'s (Not a Number) through its cables.

Since it is incorrect to assume that NaN's are for instance zero (a way to make the cables not disappear) I highly doubt this issue will ever be resolved.

Since the `waveshaper` and `expression` modules allow any mathematical formula it is almost impossible for there to be a check on if a formula can cause `NaN`'s to occur so there is also no way to catch this in a similar way syntax errors are caught.

In my opinion an issue like this should be resolved by the person writing the expression as opposed to Bespoke or its developers.

There is another aspect to this as well. Clearly a division by zero is invalid math and thus should be obvious to the user that something is wrong. If no `NaN`'s were propagated or if the cables don't "glitch" when `NaN`'s are present there is nearly no way to see or detect these from occurring especially if the input values to the expression are modulated.

Maybe the propagation of `NaN`'s should be made even more obvious?

**Comment by crshrprt** [comment]
The glitch here is about the "unrecoverable" state that happens sometimes when a division by zero occurs. As soon there isn't a division by zero anymore everything should be back to normal. For what should happen when NaN's occur I have no strong opinions.

**Comment by NoxyNixie** [comment]
Okay there is a patch in the pipline that makes NaN values very noticable: #1074 

![BespokeSynth_20230123_211848](https://user-images.githubusercontent.com/211381/214145807-77d2734c-d1d8-4180-94d4-039cb1f4db1a.gif)

Can you provide us with a savestate that can produce this unrecoverable NaN in cables state?

**Comment by NoxyNixie** [comment]
![image](https://user-images.githubusercontent.com/211381/214154873-e762da11-f6fe-46c7-ad59-77ae13e7bb8c.png)
