### ISSUE TITLE
CV not transmitting information after savestate load

### ISSUE THREAD

**Issue by Angramme** [BespokeSynth/BespokeSynth#991]
## Build info

bespoke NIGHTLY 1.1.0 (Dec 15 2022 04:37:52) - Windows 10 - HEAD 4f00ab8

## Steps To Reproduce

1. Open Bespoke
2. Load the savestate [bug_report.zip](https://github.com/BespokeSynth/BespokeSynth/files/10252227/bug_report.zip)
3. Try using the keyboard module and observe that it has no effect
4. Disconnect CV going from "pitchtocv" to "randomnote"'s "pitch" 
5. Reconnect CV from "pitchtocv" to "randomnote"'s "pitch"  
6. Try using the keyboard and observe that it changes the pitch
7. Ponder

## Expected vs. actual behavior

1. Open Bespoke
2. Load the savestate [bug_report.zip](https://github.com/BespokeSynth/BespokeSynth/files/10252227/bug_report.zip)
3. Try using the keyboard module and observe that it changes the pitch

**Comment by NoxyNixie** [comment]
I looked at this and found why it seems it does not work.

The connection actually works however the min and max (especially the max) slider value of the `pitchtocv` modules are not loaded from the savestate you provided since it was made with a version that did not save these. This bug was fixed a while ago and if you recreate your patch (or "fix" the existing one) and save with the latest version the min and max values will be properly saved.
